language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt --use-mirrors
# command to run tests, e.g. python setup.py test
script: nosetests --cover-branches --with-coverage --cover-erase --cover-package=odblib
# Coveralls statistics
after_success: coveralls
